apiVersion: microcks.github.io/v1alpha1
kind: MicrocksInstall
metadata:
  name: microcks
spec:
  # Add fields here
  name: microcks
  version: "latest"
  microcks: 
    replicas: 1
  postman:
    replicas: 1
  keycloak:
    install: true
    persistent: true
    volumeSize: 1Gi
    replicas: 1
    #serviceAccount: microcks-serviceaccount
    #serviceAccountCredentials: ab54d329-e435-41ae-a900-ec6b3fe15c54
  mongodb:
    install: true
    persistent: true
    volumeSize: 2Gi
    replicas: 1
  features:
    repositoryFilter:
      enabled: true
      labelKey: app
      labelLabel: Application
      labelList: app,status
    async:
      enabled: true
      defaultBinding: KAFKA
      defaultFrequency: 10
      kafka:
        install: true